name: "logiEx"
version: "3"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    container_name: frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

